### PR TITLE
Feature/initial examples add

### PR DESCRIPTION
**Pull request by CharlesPool**
Please review initial examples and setup for 2017.0 branch

### CODE REVIEW

**Comment by CarlosHerrero** [comment]
Hi, three copies of .exe files can be found after building the solution.
The TSEP file was not created.
What is the goal of the example?

**Comment by CharlesPool** [comment]
Three copies of exe is expected: intermediate output, output, and installer binaries. This example created dimensions of anchor bolts in existing drawing view, model is attached as zip file. TSEP is not created by msbuild automatically, is that something you want automated after output is copied to installer sub-folder?

**Comment by CarlosHerrero** [comment]
I think it should be stated more clearly what is the goal of this example repository. What people who download the project will learn from it.

**Comment by CharlesPool** [comment]
I added more detailed notes, snapshot images of project outcome, please see if this helps.

**Pull request merged**
